# Generated by Django 3.0.5 on 2020-06-16 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200617_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseslist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
