# Generated by Django 3.0.5 on 2020-06-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200606_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='records',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
    ]
