# Generated by Django 3.0.5 on 2020-06-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200606_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='records',
            new_name='item_purchased',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
