# Generated by Django 3.0.5 on 2020-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200606_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_purchased',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
    ]
